name: dental_proj
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  lottie: ^2.6.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
